from django.urls import path

from .views import (
    account_pending,
    archive_vacancy,
    change_password_confirm,
    change_password_request,
    content_manager_create,
    content_manager_edit,
    content_manager_stats,
    content_manager_videos,
    content_managers_list,
    company_chat_archive,
    company_chat_detail,
    company_chat_send_message,
    company_chats,
    company_chat_unarchive,
    company_profile_email_change_verify,
    company_profile,
    company_register,
    company_stats,
    create_vacancy,
    delete_company_profile,
    edit_company_profile,
    edit_employee_profile,
    edit_vacancy,
    employee_profile,
    export_hr_agents_csv,
    export_company_stats_csv,
    export_company_stats_pdf,
    home_comp,
    hr_agent_create,
    hr_agent_edit,
    hr_agents_list,
    import_hr_agents,
    responses_list,
    unarchive_vacancy,
    vacancy_list,
    verify_password_and_save,
)


urlpatterns = [
    path('', home_comp, name='home_comp'),
    path('register/', company_register, name='reg_comp'),
    path('profile/', company_profile, name='company_profile'),
    path('edit-profile/', edit_company_profile, name='edit_company_profile'),
    path('edit-profile/verify-email/', company_profile_email_change_verify, name='company_profile_email_change_verify'),
    path('company/verify-password/', verify_password_and_save, name='verify_password_and_save'),
    path('change-password/', change_password_request, name='change_password_request'),
    path('change-password/<str:uidb64>/<str:token>/', change_password_confirm, name='change_password_confirm'),
    path('hr-agents/', hr_agents_list, name='hr_agents_list'),
    path('hr-agents/create/', hr_agent_create, name='hr_agent_create'),
    path('hr-agents/edit/<int:employee_id>/', hr_agent_edit, name='hr_agent_edit'),
    path('hr-agents/export/', export_hr_agents_csv, name='export_hr_agents_csv'),
    path('hr-agents/import/', import_hr_agents, name='import_hr_agents'),
    path('content-managers/', content_managers_list, name='content_managers_list'),
    path('content-managers/create/', content_manager_create, name='content_manager_create'),
    path('content-managers/edit/<int:employee_id>/', content_manager_edit, name='content_manager_edit'),
    path('content-manager/stats/', content_manager_stats, name='content_manager_stats'),
    path('content-manager/videos/', content_manager_videos, name='content_manager_videos'),
    path('create-vacancy/', create_vacancy, name='create_vacancy'),
    path('vacancies/', vacancy_list, name='vacancy_list'),
    path('edit-vacancy/<int:vacancy_id>/', edit_vacancy, name='edit_vacancy'),
    path('archive-vacancy/<int:vacancy_id>/', archive_vacancy, name='archive_vacancy'),
    path('unarchive-vacancy/<int:vacancy_id>/', unarchive_vacancy, name='unarchive_vacancy'),
    path('responses/', responses_list, name='responses_list'),
    path('chats/', company_chats, name='company_chats'),
    path('chats/<int:chat_id>/archive/', company_chat_archive, name='company_chat_archive'),
    path('chats/<int:chat_id>/unarchive/', company_chat_unarchive, name='company_chat_unarchive'),
    path('chats/<int:chat_id>/', company_chat_detail, name='company_chat_detail'),
    path('chats/<int:chat_id>/send/', company_chat_send_message, name='company_chat_send_message'),
    path('stats/', company_stats, name='company_stats'),
    path('stats/export-csv/', export_company_stats_csv, name='export_company_stats_csv'),
    path('stats/export-pdf/', export_company_stats_pdf, name='export_company_stats_pdf'),
    path('account/pending/', account_pending, name='account_pending'),
    path('vacancy/<int:vacancy_id>/edit/', edit_vacancy, name='edit_vacancy'),
    path('employee/profile/', employee_profile, name='employee_profile'),
    path('employee/profile/edit/', edit_employee_profile, name='edit_employee_profile'),
    path('delete/', delete_company_profile, name='delete_company_profile'),
]
