# Generated by Django 5.2.2 on 2026-02-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihh_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'db_table': 'skills',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('applicant', 'Соискатель'), ('company', 'Владелец компании'), ('staff', 'Сотрудник компании'), ('adminsite', 'Администратор сайта')], default='applicant', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='apihh_main.applicant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.skill')),
            ],
            options={
                'verbose_name': 'Навык соискателя',
                'verbose_name_plural': 'Навыки соискателей',
                'db_table': 'applicant_skills',
                'unique_together': {('applicant', 'skill')},
            },
        ),
    ]
