# Generated by Django 5.2.11 on 2026-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihh_main', '0004_vacancy_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_avatars/%Y/%m/%d/'),
        ),
    ]
