# Generated by Django 5.2.2 on 2026-04-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihh_main', '0006_applicantinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinterest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VacancyCategorySuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=80, unique=True, verbose_name='Нормализованное имя категории')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_category_suggestions', to='apihh_main.company', verbose_name='Компания')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_vacancy_category_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vacancy_category_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Заявка на новую категорию вакансии',
                'verbose_name_plural': 'Заявки на новые категории вакансий',
                'db_table': 'vacancy_category_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
