# Generated by Django 5.2.2 on 2026-02-08 19:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код действия')),
                ('name', models.CharField(max_length=100, verbose_name='Название действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
        migrations.CreateModel(
            name='StatusResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_response_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус отклика',
                'verbose_name_plural': 'Статусы откликов',
                'db_table': 'status_responses',
            },
        ),
        migrations.CreateModel(
            name='StatusVacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_vacancies_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус вакансии',
                'verbose_name_plural': 'Статусы вакансий',
                'db_table': 'status_vacancies',
            },
        ),
        migrations.CreateModel(
            name='WorkConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_conditions_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Условие работы',
                'verbose_name_plural': 'Условия работы',
                'db_table': 'work_conditions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=80)),
                ('user_type', models.CharField(choices=[('applicant', 'Соискатель'), ('company', 'Владелец компании')], default='applicant', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField()),
                ('resume', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бэкапа')),
                ('backup_file', models.FileField(upload_to='backups/%Y/%m/%d/', verbose_name='Файл бэкапа')),
                ('backup_type', models.CharField(choices=[('full', 'Полный бэкап'), ('database', 'Только база данных'), ('media', 'Только медиафайлы')], default='database', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Бэкап',
                'verbose_name_plural': 'Бэкапы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус аккаунта')),
                ('verification_document', models.FileField(help_text='Загрузите документ в формате PDF', upload_to='company_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Подтверждающий документ (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Последнее сообщение')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.applicant', verbose_name='Соискатель')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'db_table': 'chats',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID целевого объекта')),
                ('target_content_type', models.CharField(blank=True, max_length=100, verbose_name='Тип целевого объекта')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.actiontype', verbose_name='Действие')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('target_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apihh_main.company', verbose_name='Целевая компания')),
            ],
            options={
                'verbose_name': 'Лог действий',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('site_admin', 'Администратор сайта'), ('hr', 'HR агент'), ('content_manager', 'Контент-менеджер')], max_length=30)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='apihh_main.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('experience', models.CharField(blank=True, choices=[('Без опыта', 'Без опыта'), ('1-3 года', '1-3 года'), ('3-6 лет', '3-6 лет'), ('от 6 лет', 'от 6 лет')], max_length=20, null=True)),
                ('city', models.CharField(default='Москва', max_length=100)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Маркетинг', 'Маркетинг'), ('Продажи', 'Продажи'), ('HR', 'HR')], default='IT', max_length=50)),
                ('work_conditions_details', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.company')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.statusvacancies')),
                ('work_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.workconditions')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.applicant')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.statusresponse')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'db_table': 'responses',
                'unique_together': {('applicants', 'vacancy')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sender_type', models.CharField(choices=[('applicant', 'Соискатель'), ('company', 'Компания'), ('hr-agent', 'HR-агент')], max_length=10, verbose_name='Тип отправителя')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('system', 'Системное'), ('file', 'Файл')], default='text', max_length=10, verbose_name='Тип сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('system_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Системное действие')),
                ('is_read_by_applicant', models.BooleanField(default=False, verbose_name='Прочитано соискателем')),
                ('is_read_by_company', models.BooleanField(default=False, verbose_name='Прочитано компанией')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apihh_main.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('related_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apihh_main.response', verbose_name='Связанный отклик')),
                ('related_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apihh_main.vacancy', verbose_name='Связанная вакансия')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.vacancy', verbose_name='Вакансия'),
        ),
        migrations.CreateModel(
            name='VacancyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='vacancy_videos/%Y/%m/%d/', verbose_name='Видео файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='apihh_main.employee')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='apihh_main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Видео вакансии',
                'verbose_name_plural': 'Видео вакансий',
                'db_table': 'vacancy_videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.applicant', verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные вакансии',
                'db_table': 'favorites',
                'unique_together': {('applicant', 'vacancy')},
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('spam', 'Спам'), ('fraud', 'Мошенничество'), ('inappropriate', 'Неуместный контент'), ('discrimination', 'Дискриминация'), ('false_info', 'Ложная информация'), ('other', 'Другое')], max_length=50, verbose_name='Тип жалобы')),
                ('description', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('reviewed', 'Рассмотрено'), ('rejected', 'Отклонено'), ('resolved', 'Решено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подавший жалобу')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'db_table': 'complaints',
                'unique_together': {('vacancy', 'complainant')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('vacancy', 'applicant')},
        ),
        migrations.CreateModel(
            name='VacancyVideoLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.applicant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.vacancyvideo')),
            ],
            options={
                'db_table': 'vacancy_video_likes',
                'unique_together': {('applicant', 'video')},
            },
        ),
        migrations.CreateModel(
            name='VacancyVideoView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.applicant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihh_main.vacancyvideo')),
            ],
            options={
                'db_table': 'vacancy_video_views',
                'unique_together': {('applicant', 'video')},
            },
        ),
    ]
