# Generated by Django 5.2.11 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihh_main', '0005_applicant_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Маркетинг', 'Маркетинг'), ('Продажи', 'Продажи'), ('HR', 'HR')], max_length=50)),
                ('applicant', models.ForeignKey(on_delete=models.CASCADE, related_name='interests', to='apihh_main.applicant')),
            ],
            options={
                'verbose_name': 'Р�РЅС‚РµСЂРµСЃ СЃРѕРёСЃРєР°С‚РµР»СЏ',
                'verbose_name_plural': 'Р�РЅС‚РµСЂРµСЃС‹ СЃРѕРёСЃРєР°С‚РµР»РµР№',
                'db_table': 'applicant_interests',
                'unique_together': {('applicant', 'category')},
            },
        ),
    ]
