# Generated by Django 5.2.2 on 2026-04-08 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihh_main', '0007_alter_applicantinterest_id_vacancycategorysuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='applicant_resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'rtf', 'txt'])]),
        ),
    ]
