# Generated by Django 5.2.2 on 2026-04-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihh_main', '0008_applicant_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancycategorysuggestion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_category_suggestions', to='apihh_main.company', verbose_name='Компания'),
        ),
    ]
